---
title: "Cleaning Video Game Data"
author: "George Harley Mejia"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## View and summarise the data to identify problems
  First, the initial data set (Video_Games_Data) csv file was loaded, viewed, and summarised to identify any noticable outliers or missing values. There were a substantial number of missing values for key variables in our analysis that needed to be cleaned. Furthermore, upon inspection of a handful of randomly selected observations, it was found that some had missing values for the critic score and user score variables that should be available on the website the data was originally scraped from. Cross-reference of Metacritic.com reveal that the web pages where the data was found did in fact had data for the missing values.

## Web Scrape Metacritic
  With the issues identified, the next step was a web scrape of the Metacritic website to gather as many of the missing values for the critic score and the user score as possible. The web scrape resulted in a csv file with the variables Name, Platform, Critic_Score, and User_Score, which was then loaded into the workspace (Meta_Critic_Data). 

## Join both data sets to include new variables
  Then, both data sets were joined by a left join with Video_Games_Data on the left and Meta_Critic_Data on the right with the “by” argument equal to the Name and Platform variables. The join resulted in a new data set (Clean_Video_Games_Data) which contained all observations and variables from the Video_Games_Data table and the Critic_Score and User_Score variables from the Meta_Critic_Data table. 

## The next issue that needed to be cleaned were the missing values. 
# Change "tbd" to "NA"
  First, the user scores from the Video_Games_Data table (User_Score.x) had a special character called “tbd” which means “to be determined” on the Metacritic website and is given to games that haven’t yet been rated, but will. The values with “tbd” are essentially the same as if that observation had a missing value, so all instances of the character “tbd” were changed to a missing value, or an NA.
  
# Replace any older or missing values with the newer scraped values
  Next, any older values or missing values the Critic_Score.x and User_Score.x variables (from Video_Games_Data) are replaced by any values that aren’t missing from the Critic_Score.y and User_Score.y variables (from Meta_Critic_Data) using an ifelse function. Unfortunately, this only results in about 300 observations of missing values to be replaced with new values for both variables.
  
# Filter out any missing values for important variables
  Next, the rest of the missing values of key variables in the data set need to be filtered out. Of the six variables that still contain missing values only four are important to our analysis: User_Score.x, Critic_Score.x, Developer, and Rating. Filtering out the missing values from User_Score.x, Critic_Score.x, and Rating is enough to eliminate all of the missing values from the key variables. 
  
# Remove extraneous variables and rename essential variables
  Finally, the extraneous variables Critic_Score.y and User_Score.y are removed from the data and the variables Critic_Score.x and User_Score.x are renamed into Critic_Score and User_Score, respectively. The final cleaned data set contains 7024 observations.



